-- USERS
CREATE TABLE users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name TEXT NOT NULL,
    email TEXT UNIQUE,
    phone TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    user_type TEXT NOT NULL CHECK (user_type IN ('client', 'courier', 'admin'))
);


-- COURIERS
CREATE TABLE couriers (
    user_id INT PRIMARY KEY,
    vehicle_type TEXT,
    is_available BOOLEAN DEFAULT TRUE,

    FOREIGN KEY (user_id) REFERENCES users(user_id)
);

-- RESTAURANTS
CREATE TABLE restaurants (
    restaurant_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_name TEXT NOT NULL,
    cuisine_type TEXT,
    restaurant_latitude DOUBLE PRECISION,
    restaurant_longitude DOUBLE PRECISION,

    creator_user_id INT,
    FOREIGN KEY (creator_user_id) REFERENCES users(user_id)
);

-- ORDERS
CREATE TABLE orders (
    order_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id INT NOT NULL,
    restaurant_id INT NOT NULL,
    courier_id INT,
    order_status TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (client_id) REFERENCES users(user_id),
    FOREIGN KEY (restaurant_id) REFERENCES restaurants(restaurant_id),
    FOREIGN KEY (courier_id) REFERENCES couriers(user_id)
);

-- ORDER EVENTS (histórico)
CREATE TABLE order_events (
    event_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INT NOT NULL,
    event_status TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (order_id) REFERENCES orders(order_id)
);

-- ORDER ITEMS
CREATE TABLE order_items (
    item_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INT NOT NULL,
    item_name TEXT NOT NULL,
    quantity INT NOT NULL CHECK (quantity > 0),

    FOREIGN KEY (order_id) REFERENCES orders(order_id)
);