-- USERS
CREATE TABLE IF NOT EXISTS users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name TEXT NOT NULL,
    email TEXT UNIQUE,
    phone TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    user_type TEXT NOT NULL CHECK (user_type IN ('client', 'courier', 'admin'))
);

-- COURIERS
CREATE TABLE IF NOT EXISTS couriers (
    user_id INT PRIMARY KEY,
    vehicle_type TEXT,
    is_available BOOLEAN DEFAULT TRUE,
    CONSTRAINT couriers_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(user_id)
);

-- RESTAURANTS
CREATE TABLE IF NOT EXISTS restaurants (
    restaurant_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_name TEXT NOT NULL,
    cuisine_type TEXT,
    restaurant_latitude DOUBLE PRECISION,
    restaurant_longitude DOUBLE PRECISION,
    creator_user_id INT,
    FOREIGN KEY (creator_user_id) REFERENCES users(user_id)
);

-- ORDERS
CREATE TABLE IF NOT EXISTS orders (
    order_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id INT NOT NULL,
    restaurant_id INT NOT NULL,
    courier_id INT,
    order_status TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (client_id) REFERENCES users(user_id),
    FOREIGN KEY (restaurant_id) REFERENCES restaurants(restaurant_id),
    FOREIGN KEY (courier_id) REFERENCES couriers(user_id)
);

-- ORDER EVENTS
CREATE TABLE IF NOT EXISTS order_events (
    event_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INT NOT NULL,
    event_type TEXT NOT NULL,
    from_status TEXT,
    to_status TEXT,
    event_message TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (order_id) REFERENCES orders(order_id)
);

-- ORDER ITEMS
CREATE TABLE IF NOT EXISTS order_items (
    item_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INT NOT NULL,
    item_name TEXT NOT NULL,
    quantity INT NOT NULL CHECK (quantity > 0),
    FOREIGN KEY (order_id) REFERENCES orders(order_id)
);

CREATE INDEX IF NOT EXISTS idx_orders_client_created
ON orders (client_id, created_at, order_id);

CREATE INDEX IF NOT EXISTS idx_orders_courier_status_created
ON orders (courier_id, order_status, created_at, order_id);

CREATE INDEX IF NOT EXISTS idx_order_items_order_id
ON order_items (order_id);

CREATE INDEX IF NOT EXISTS idx_order_events_order_created
ON order_events (order_id, created_at, event_id);